# Generated by Django 5.2.8 on 2025-11-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rss_kb', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='monitor.monitorrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
